In [1]:
#函式筆記
# np.linalg.matrix_rank()  #計算矩陣的Rank

# np.hstack()  #堆疊矩陣
    #a=[[1],[2],[3]]
    #b=[[1],[2],[3]]
    #c=[[1],[2],[3]]
    #d=[[1],[2],[3]]
    #print(np.hstack((a,b,c,d)))

    #输出：
     #[[1 1 1 1]
     # [2 2 2 2]
     # [3 3 3 3]]

#A.shape[1]  #to get the column number of A

In [2]:
#Hint
# By (Proposition 1)
#  if (Rank(A) == Rank(Ab))
#        𝐀x = 𝐛 is consistent. #表示 Ax=b 有解


# By (Proposition 2)
#  if (Rank(A) == n)
#       A的行之間互相是 linearly independent，代表有唯一解
#  else
#       線性相依，代表不只一個解

In [3]:
import numpy as np
def solve_linear_equation(A, b):
   # enter your code here, and remove the following line (30%)
   
   rank_A = np.linalg.matrix_rank(A) #計算RankA
   AB = np.hstack((A, b)) #將A和b合併
   rank_AB = np.linalg.matrix_rank(AB) #計算Ab的Rank

   # By Proposition 1 and Proposition 2
   if rank_AB == rank_A: #𝐀x = 𝐛 is consistent
        if rank_A == A.shape[1]:
            return 1 # Only one solution
        else:
            return 0 # Infinitely many solutions
   else:
        return -1 # 𝐀x = 𝐛 is not consistent #No solutions
   return 0

def flag_to_message(flag):
   if flag == 1:
     print('The linear system Ax=b has only one solution.')
   elif flag == 0:
     print('The linear system Ax=b has infinitely many solutions.')
   elif flag == -1:
     print('The linear system Ax=b has no solutions.')
   else:
     print('Unknown flag!')

def get_input_data(input_id):
   if input_id == 'case1': 
     A = np.array([[3, 2, -1], [6, -1, 3], [1, 10, -2]])
     b = np.array([[-7], [-4], [2]])
   elif input_id == 'case2':
     A = np.array([[4, -1, 3], [21, -4, 18], [-9, 1, -9]])
     b = np.array([[5], [7], [-8]])
   elif input_id == 'case3':
     A = np.array([[7, -4, 1], [3, 2, -1], [5, 12, -5]])
     b = np.array([[-15], [-5], [-5]])
   return A, b

if __name__ == '__main__':
   for case in ['case1', 'case2', 'case3']:
     A, b = get_input_data(case)
     print(case)
     print('A =', A, 'b =', b.T)
     flag = solve_linear_equation(A, b)
     flag_to_message(flag)
     if flag == 1:
       print('The solution is ', np.linalg.solve(A, b))
     print()


case1
A = [[ 3  2 -1]
 [ 6 -1  3]
 [ 1 10 -2]] b = [[-7 -4  2]]
The linear system Ax=b has only one solution.
The solution is  [[-2.]
 [ 1.]
 [ 3.]]

case2
A = [[ 4 -1  3]
 [21 -4 18]
 [-9  1 -9]] b = [[ 5  7 -8]]
The linear system Ax=b has no solutions.

case3
A = [[ 7 -4  1]
 [ 3  2 -1]
 [ 5 12 -5]] b = [[-15  -5  -5]]
The linear system Ax=b has infinitely many solutions.



In [4]:
# Can we use np.linalg.solve() to determine whether 𝐀𝐱=𝐛 is consistent? Explain the reason for your answer. (5%)
# Write down your answer here.

#ANS
# 可以的，當我們使用 np.linalg.solve() 來解決 Ax=b 時，分成以下3種情況:

#A:唯一解: 直接輸出答案
#B:無限解: 輸出無限解中其中一個解
#C:無解: 會顯示Error

#所以如果單純只是要看看 𝐀𝐱=𝐛 是否 consistent， np.linalg.solve() 是可以做到的。

In [5]:
# Given matrix 𝐀 of dimension (m,n). If rank(𝐀)=𝑛, can we infer that 𝐀𝐱=𝐛 is consistent? Explain the reason for your answer. (5%)
# Write down your answer here.

#ANS
#可以的，如果Rank(A)=就代表A的每一列都跟b是線性獨立的，代表b可以用A的列的一組唯一一組組合來表示，所以Ax=b是consistent的。